### ISSUE TITLE
Possible to lose compass behind Earth

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#198] opened 2024-07-18 12:23 UTC
**Test device**
Dell

**Operating System**
Win11

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1110 in Studio if `faradaysElectromagneticLab.barMagnetScreen.view.earthNode.inputEnabledProperty` is set to false, it is possible to lose the compass behind Earth. The user would have to switch to keyboard nav or press Reset All in that situation. 

**Steps to reproduce**
1. In the Studio wrapper set `faradaysElectromagneticLab.barMagnetScreen.view.earthNode.inputEnabledProperty` to false
2. In the Simulation tab of the Preferences menu toggle Add "Earth" Checkbox
3. Check Earth Checkbox in the sim
4. Grab the compass with the mouse and move it behind the Earth and release
5. Try to grab the compass

**Comment by pixelzoom** [comment] 2024-07-18 16:10
Fixed in https://github.com/phetsims/faradays-electromagnetic-lab/commit/2dd901f90922beb21e3848ef10032ff9b212f431. When `earthNode.inputEnabledProperty` is set to false, I am now setting `pickable: false`.  This causes scenery to ignore earthNode when doing "hit testing", and you can grab things (like the compass) that are behind earthNode.

@Nancy-Salpepi please review in main, close if OK.

**Comment by pixelzoom** [comment] 2024-07-18 16:16
FYI... The fix in https://github.com/phetsims/faradays-electromagnetic-lab/commit/2dd901f90922beb21e3848ef10032ff9b212f431 feels more like a workaround, and I wonder why scenery hit tests a Node whose inputEnabled is false.  I created a general issue about this,  see https://github.com/phetsims/scenery/issues/1647.

**Comment by pixelzoom** [comment] 2024-07-18 16:30
FYI part 2 ... According to @jonathanolson in https://github.com/phetsims/scenery/issues/1647, the current behavior of inputEnabledProperty is expected.  So https://github.com/phetsims/faradays-electromagnetic-lab/commit/2dd901f90922beb21e3848ef10032ff9b212f431 is a solution, not a workaround, and (in general) will need to be applied on a case-by-case basis.

**Comment by Nancy-Salpepi** [comment] 2024-07-18 16:33
The good news is I can now grab the compass when it is behind the Earth. 
Bad news is, I can move the Earth when its inputEnabledProperty is false by grabbing onto the magnet and moving it. 


https://github.com/user-attachments/assets/d90e13e4-b111-4b93-9e8d-4977d89dd829

**Comment by arouinfar** [comment] 2024-07-18 16:44
>  I can move the Earth when its inputEnabledProperty is false by grabbing onto the magnet and moving it.

I think it's reasonable to expect clients to set `inputEnabledProperty: false` for both the Earth and the magnet.

**Comment by pixelzoom** [comment] 2024-07-18 16:46
> Bad news is, I can move the Earth when its inputEnabledProperty is false by grabbing onto the magnet and moving it.

By design, earthNode and barMagnetNode have individual `inputEnabledProperty` elements.  If you want _neither_ to be draggable, then you need to set both `earthNode.inputEnabledProperty ` and `barMagnetNode.inputEnabledProperty` to false. @arouinfar do you want to change anything about this?

**Comment by pixelzoom** [comment] 2024-07-18 16:49
We could uninstrument `earthNode.inputEnabledProperty` and derived it's value from `barMagnetNode.inputEnabledProperty`.   So if `barMagnetNode.inputEnabledProperty` is set to false, then earthNode would also be NOT draggable.  That would be a PhET-iO API change. And I'm not convinced that it's worth the trouble.

**Comment by arouinfar** [comment] 2024-07-18 16:50
>  @arouinfar do you want to change anything about this?

No, nothing I want to change here. I think it's reasonable for clients to set `inputEnabledProperty: false` for both the Earth and the magnet. The examples.md already covers this case. Closing.

**Closed as completed by arouinfar** 2024-07-18 16:50 UTC
Labels: type:bug, status:ready-for-review
