### ISSUE TITLE
Disappearing current particles

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#204] opened 2024-07-26 16:37 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
Found in https://github.com/phetsims/qa/issues/1119
I had one instance of the conventional current particles disappearing from the sim even though the checkbox was checked. Refreshing the page fixed it and I haven't been able to reproduce it. I had been off the page working on other things, and when I came back this had occurred.

**Visuals**
![gone](https://github.com/user-attachments/assets/05af0174-95dd-49ce-a215-d5194508a8a5)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Generator‬
URL: https://phet-dev.colorado.edu/html/generator/1.0.0-rc.1/phet/generator_all_phet.html
Version: 1.0.0-rc.1 2024-07-18 18:17:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment] 2024-07-26 18:32
Tagging https://github.com/phetsims/qa/issues/1116 so this shows up in the main RC issue.

**Comment by pixelzoom** [comment] 2024-07-26 22:09
I cannot reproduce this, and @KatieWoe only saw it once, so I don't have anything I can investigate. I discussed with @arouinfar, and she said that she's seen sims be in odd states if she leaves and comes back some time later.  We're confident that this will not be a problem in practice, so closing this issue as "won't fix".  But thanks for reporting!

**Closed as completed by pixelzoom** 2024-07-26 22:09 UTC
Labels: type:bug
