### ISSUE TITLE
'g' in Bar Magnet getting clipped through 

### ISSUE THREAD

**Issue by JaronDroder** [phetsims/faradays-electromagnetic-lab#200] opened 2024-07-25 16:51 UTC
**Test Device**
Alienware m15 R7 

**Operating System**
Win 22H2  

**Browser**
Chrome 127.0.6533.73

 **Problem Description**
 
For  https://github.com/phetsims/qa/issues/1117

 On the Bar Magnet section of the sim, there is some sort of clip through when the bar magnet or the bar magnet with earth is moved close to the menu in the top right. When moving the magnet around this area, I am seeing the bottom part of the 'g'  in the title 'Bar Magnet' can be cut off if the magnet is at a specific location. I thought it might be the magnetic field beneath the menu causing this, but even with the 'Magnetic Field (B)' turned off, the issue persists. 

I first found the bug in For https://github.com/phetsims/qa/issues/1117, but it also seems to be present in https://github.com/phetsims/qa/issues/1116.
 
**Steps to Reproduce**

1. Select the Bar Magnet screen for the sim

2. Move the bar magnet close to the top right menu and move it around.   I found it somewhat difficult to find this spot at times, but I hope the gifs I provided can make it easier. 

Visuals

 
![barmagnetgbug](https://github.com/user-attachments/assets/afc2ac94-35a5-458b-bed3-8c5fd2fd60c1)
![barmagnetgbug2](https://github.com/user-attachments/assets/48509362-5ce5-433d-9d54-de5da6031550)

**Comment by pixelzoom** [comment] 2024-07-25 17:07
This was not reproducible on macOS + Chrome 126.0.6478.183.   I updated to Chrome 127.0.6533.73 (latest), and still could not reproduce.  So this seems to be specific to Windows.

What's probably happening here is:  The earth Node has a rectangular bounds.  When you're dragging the earth, those bounds determine which parts of the screen become "dirty" and need to be repainted.  Text bounds are notoriously inaccuarate on some platforms.  So when the top of the earth Node's bounds intersects the bottom of the "Bar Magnet" text, the bottom of the "g" is not getting repainted. 

This falls into the category of "scenery graphics artifacts", and we have typically not been addressing them unless they affect usability or are severe. So my recommendation is to close this as "won't fix". @arouinfar do you agree?

**Comment by arouinfar** [comment] 2024-07-25 17:10
Nice find @JaronDroder!

> This falls into the category of "scenery graphics artifacts", and we have typically not been addressing them unless they affect usability or are severe. So my recommendation is to close this as "won't fix". @arouinfar do you agree?

I agree @pixelzoom. Let's close as wont-fix.

**Closed as not planned by arouinfar** 2024-07-25 17:10 UTC
Labels: type:bug, type:wontfix

**Comment by arouinfar** [comment] 2024-07-25 17:11
Tagging https://github.com/phetsims/qa/issues/1116 so this issue shows up on the main RC issue.
