### ISSUE TITLE
Error: Assertion failed: unexpected emfProperty.value

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#149] opened 2024-03-28 14:30 UTC
Discovered while working on #103, while testing the state wrapper on macbook air m1 chrome, I believe I changed to the AC source right before this happened:

```
PhetioClient.ts:2052 Uncaught (in promise) Error: Assertion failed: unexpected emf: -3252.5441996147506
    at window.assertions.assertFunction (assert.js:28:13)
    at Transformer.ts:77:17
    at TinyProperty.notifyLoop (TinyEmitter.ts:213:7)
    at TinyProperty.emit (TinyEmitter.ts:185:18)
    at Property._notifyListeners (ReadOnlyProperty.ts:336:23)
    at PhaseCallback.listener (ReadOnlyProperty.ts:384:47)
    at PropertyStateHandler.attemptToApplyPhases (PropertyStateHandler.ts:273:41)
    at PropertyStateHandler.undeferAndNotifyProperties (PropertyStateHandler.ts:193:12)
    at PropertyStateHandler.ts:88:12
    at TinyEmitter.notifyLoop (TinyEmitter.ts:213:7)
```

<img width="2241" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/36cbc467-d706-4a8f-8448-8d57006292d0">

I confirmed that these steps reproduce the problem:
1. Launch the simulation
2. Open the "Transformer" screen
3. Press the AC current source radio button

**Comment by samreid** [comment] 2024-03-28 14:31
This is also occurring on CT

**Comment by pixelzoom** [comment] 2024-03-29 01:44
Assertion message changed in the above commit, and updated in the issue title.

Reproduced in my working copy with http://localhost:8080/phet-io-wrappers/state/?sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&audio=disabled

This is related to https://github.com/phetsims/faradays-electromagnetic-lab/issues/124, the workaround for zeroing out EMF when switching power supplies.  The relevant code in Transformer.ts is:

```ts
    // Workaround for https://github.com/phetsims/faradays-electromagnetic-lab/issues/92, to ignore the EMF induced
    // by switching power supplies. Step the pickup coil twice, so that there is effectively no induced EMF.
    this.electromagnet.currentSourceProperty.lazyLink( () => {
      this.pickupCoil.step( ConstantDtClock.DT ); // EMF may be induced by changing from oldCurrentSource to newCurrentSource.
      this.pickupCoil.step( ConstantDtClock.DT ); // No EMF is induced because there is no flux change in newCurrentSource.
      assert && assert( this.pickupCoil.emfProperty.value === 0, `unexpected emfProperty.value: ${this.pickupCoil.emfProperty.value}` );
    } );
```

I'm glad I added this assertion, because something is clearly not right when state is restored.  Maybe I need to add an`isSettingPhetioStateProperty` guard to skip this code when restoring PhET-iO state.

**Comment by pixelzoom** [comment] 2024-03-29 20:57
> Maybe I need to add an`isSettingPhetioStateProperty` guard to skip this code when restoring PhET-iO state.

That's what I did in https://github.com/phetsims/faradays-electromagnetic-lab/commit/f3773ceb9d80d9aab1ae1de2db9c9dbc45b60ab9. It seems to resolve the problem in my working copy, and we'll see what CT has to say.   But I don't understand why it's necessary, or why it's even effective.   And I'm concerned that it may result in incorrect behavior when switching power supplies.

**Comment by pixelzoom** [comment] 2024-04-03 04:13
The code identified in https://github.com/phetsims/faradays-electromagnetic-lab/issues/149#issuecomment-2026453746 has been replaced by a new implementation for avoiding induced EMF when changing power supplies -- see #124. So I've removed the `isSettingPhetioStateProperty` guard, and we'll see if CT has a problem with the new implementation.

**Comment by pixelzoom** [comment] 2024-04-05 16:23
Still occurring in CT, most recently:

```
aradays-electromagnetic-lab : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/phet-io-wrappers/state/?sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712311463115%22%2C%22timestamp%22%3A1712329940914%7D
Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/assert/js/assert.js:28:13)
at assert (dataStream.ts:299:14)
at end (PhetioObject.ts:514:29)
at phetioEndEvent (phetioCommandProcessor.ts:254:17)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1712311463115%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dfaradays-electromagnetic-lab%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712311463115%22%2C%22timestamp%22%3A1712329940914%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1712311463115%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dfaradays-electromagnetic-lab%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712311463115%22%2C%22timestamp%22%3A1712329940914%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/phet-io-wrappers/state/?sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712311463115%22%2C%22timestamp%22%3A1712329940914%7D
[ATTACHED]
[NAVIGATED] about:blank
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?brand=phet-io&ea&postMessageOnError&sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712311463115%22%2C%22timestamp%22%3A1712329940914%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/faradays-electromagnetic-lab/faradays-electromagnetic-lab_en.html?brand=phet-io&ea&postMessageOnError&sim=faradays-electromagnetic-lab&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-electromagnetic-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712311463115%22%2C%22timestamp%22%3A1712329940914%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: unexpected emfProperty.value: -2094.1448268091262
[CONSOLE] Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[PAGE ERROR] Error: Error: Assertion failed: unexpected emfProperty.value: -2094.1448268091262
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/assert/js/assert.js:28:13)
at PickupCoil.clearEMF (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/faradays-electromagnetic-lab/js/common/model/PickupCoil.js:199:15)
at http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/faradays-electromagnetic-lab/js/transformer/model/Transformer.js:57:77
at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/axon/js/ReadOnlyProperty.js:258:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/axon/js/ReadOnlyProperty.js:303:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/tandem/js/PhetioObject.js:439:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1712311463115/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 4/5/2024, 4:04:23 AM
```

**Comment by pixelzoom** [comment] 2024-04-05 16:23
Meeting with @zepumph scheduled for Tue 4/9 @ 11AM MT.

**Comment by pixelzoom** [comment] 2024-04-09 17:41
@pixelzoom note to self.  The reason that clearEMF fails is that Property changes made while setting state are silently ignored.  In ReadOnlyProperty.ts:

```ts
  protected set( value: T ): void {

    // state is managed by the PhetioStateEngine.
    // We still want to set Properties when clearing dynamic elements, see https://github.com/phetsims/phet-io/issues/1906
    const setManagedByPhetioState = isPhetioStateEngineManagingPropertyValuesProperty.value &&
                                    !isClearingPhetioDynamicElementsProperty.value &&
                                    this.isPhetioInstrumented() && this.phetioState &&

                                    // However, DerivedProperty should be able to update during PhET-iO state set
                                    this.isSettable();

    if ( !setManagedByPhetioState ) {
      this.unguardedSet( value );
    }
  }
```

**Comment by pixelzoom** [comment] 2024-04-09 18:49
The reason that clearEMF fails is that Property changes made while setting state are silently (!) ignored.  In ReadOnlyProperty.ts:

```ts
  protected set( value: T ): void {

    // state is managed by the PhetioStateEngine.
    // We still want to set Properties when clearing dynamic elements, see https://github.com/phetsims/phet-io/issues/1906
    const setManagedByPhetioState = isPhetioStateEngineManagingPropertyValuesProperty.value &&
                                    !isClearingPhetioDynamicElementsProperty.value &&
                                    this.isPhetioInstrumented() && this.phetioState &&

                                    // However, DerivedProperty should be able to update during PhET-iO state set
                                    this.isSettable();

    if ( !setManagedByPhetioState ) {
      this.unguardedSet( value );
    }
  }
```

So in https://github.com/phetsims/faradays-electromagnetic-lab/commit/8e7ada82d0b66255055caaeaab26a269285bf51e, it's necessary to short-circuit the call to `clearEMF` when setting state:

```ts
    // Ignore the EMF induced by switching power supplies. Do not do this when setting PhET-iO state because Property
    // changes made by clearEMF will be ignored, resulting in failure of clearEMF.
    // See https://github.com/phetsims/faradays-electromagnetic-lab/issues/149.
    this.electromagnet.currentSourceProperty.lazyLink( () => {
      if ( !isSettingPhetioStateProperty.value ) {
        this.pickupCoil.clearEMF();
      }
    } );
```

I'll leave this open for a few CT cycles to confirm that this resolves the problem.

**Comment by pixelzoom** [comment] 2024-04-09 21:53
CT is happy. Closing.

**Closed as completed by pixelzoom** 2024-04-09 21:53 UTC
Labels: type:bug, dev:code-review, dev:phet-io, status:ready-for-review
