### ISSUE TITLE
Large flash sometimes occurs when switching from AC source to battery

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#92] opened 2024-03-01 18:35 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1051 on the Transformer Screen:
With the bulb placed over the transformer, switching from AC source to the battery sometimes results in a large flash of light. This seems to happen right after the AC source hits a trough. The size of the flash is smaller when the switch occurs during the ascent. No flash occurs when switching to the battery when the AC source is at a peak or on the descent. 

**Steps to reproduce**
1. On the Transformer Screen move the bulb over the transformer
2. Switch back and forth between the AC source and the Battery

**Visuals**

(This video has more coils than in Steps above)

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/12a94c05-a3b6-435b-8258-01b173aa8b1d

<details>
roubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.16/phet/faradays-electromagnetic-lab_all_phet.html
Version: 1.0.0-dev.16 2024-03-01 00:38:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
Language: en-US
Window: 1428x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment] 2024-03-01 19:05
Thanks @Nancy-Salpepi.

@pixelzoom my initial theory was that the flash was due to a large swing in voltage, but that doesn't seem to be the case. The flash happens when switching to the battery just as the AC voltage is rising out of the trough. It does not happen when descending into the trough or when at the bottom. 

Steps to reproduce:
1. Default configuration for both the electromagnet and pickup coil.
2. Center the electromagnet in the pickup coil, then select AC source.
3. Pause and step forward until the red indicator line is just after a trough:
  <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/1e0d4675-a492-4e1d-9fcf-600aeb69d901" width=300>

4. Switch to Battery, and then press the StepForwardButton once to step the model.
  <img src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/d6e6ea67-3cb1-4077-b479-b357ef5af3bf" width=430>

**Comment by pixelzoom** [comment] 2024-03-03 01:17
I believe that I see the same behavior in the Java version.

**Comment by pixelzoom** [comment] 2024-03-14 23:02
@arouinfar and I discussed this.   It would be preferrable if there was no reaction from the light bulb or voltmeter when switching between electromagnet power supplies.  Similar to pressing Reset All (see our decisions in https://github.com/phetsims/faradays-electromagnetic-lab/issues/47#issuecomment-1912387575), making sense of how changing power supplies results in a change in flux is not a learning goal, or something we want students to think about.

**Comment by pixelzoom** [comment] 2024-03-14 23:09
I thought that adding something like this to PickupCoil would do the job, but it does not:

```ts
    this.currentIndicatorProperty.lazyLink( () => {
      this._deltaFluxProperty.reset();
      this._fluxProperty.value = this.getFlux();
      this._emfProperty.reset();
    } );
```

**Comment by pixelzoom** [comment] 2024-03-18 20:42
Addressed in the above commits -- switching power supplies now results in no induced EMF.

**Comment by pixelzoom** [comment] 2024-03-18 20:42
@Nancy-Salpepi @arouinfar please review. Last on to review please close if OK.

**Comment by Nancy-Salpepi** [comment] 2024-03-18 23:34
Changes look great to me!

**Comment by arouinfar** [comment] 2024-03-19 19:37
Looks good on main, thanks @pixelzoom! Closing.

**Closed as completed by arouinfar** 2024-03-19 19:37 UTC
Labels: type:bug, status:ready-for-review
