### ISSUE TITLE
UI sound for WaterFaucetNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#90] opened 2024-02-29 22:58 UTC
Discussed at today's design meeting...

Version 1.0 of FEL will have UI sounds, and FaucetNode is currently the only element that does not have UI sound. Since sound design and implementation for FaucetNode is unlikely to be completed before this sim is published, I'll investigate adding some temporary UI sound in WaterFaucetNode.ts, the subclass of FaucetNode used in FEL.   The consensus was that the default Slider sound would be fine.

**Comment by pixelzoom** [comment] 2024-03-05 22:31
I've added temporary sounds to WaterFaucetNode, code that is specific to this sim.  I used the same sounds that are used by Slider --- blips when the value changes, bloops when we reach the min and max :)

No changes were made to FaucetNode. There is a TODO in WaterFaucetNode that refers to https://github.com/phetsims/scenery-phet/issues/840 (Sound for FaucetNode). If some tries to close that issue after adding sound to FaucetNode in common code, they will be notified that they need to remove the temporary sound is WaterFaucetNode.

@arouinfar please review, close if OK.

**Comment by arouinfar** [comment] 2024-03-06 19:43
Thanks @pixelzoom. I confirmed the FacetNode sounds like a slider on main. There are quite a lot of blips sounding as I interact with the FaucetNode. It seems like the sound is triggering every 1%, which makes sense since the mouse/touch interaction is continuous, but it doesn't sound very good. Is it possible to increase the interval at which the blip is triggered?

I have the same issue with the sound being generated by the other sliders in the sim, but I think the changes in #96 will likely resolve that.

**Comment by pixelzoom** [comment] 2024-03-06 19:47
Yes, is it possible to increase the interval at which the sound is triggered. The interval is currently 2%.  What would you prefer?

**Comment by arouinfar** [comment] 2024-03-06 20:15
Let's try 5% @pixelzoom.

**Comment by pixelzoom** [comment] 2024-03-06 20:40
Sound now plays when flowRateProperty (range 0-100%) changes by 5%.

@arouinfar please review, close if OK.

**Comment by arouinfar** [comment] 2024-03-06 23:23
Thanks @pixelzoom. I think the FaucetNode sound is still playing too often. I know it's the same interval as the other sliders in the sim, but it doesn't feel the same because FaucetNode has a much shorter track than a typical slider. Can you please increase the interval to 10%?

**Comment by pixelzoom** [comment] 2024-03-07 16:22
Changed to 10%, back to @arouinfar for review, close if OK.

**Comment by arouinfar** [comment] 2024-03-07 23:20
Thanks @pixelzoom, 10% sounds good to me. Closing.

**Closed as completed by arouinfar** 2024-03-07 23:20 UTC
Labels: dev:sound, status:ready-for-review
