### ISSUE TITLE
Loop passes through other objects

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#93] opened 2024-03-01 19:14 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1051
In the java sim and Faraday's Law the loop of wire does not let objects like the magnet pass up or down through it. This is not present in this dev test, and the loop is not solid on the top or bottom. If this is an intended change feel free to close.

**Visuals**

https://github.com/phetsims/faradays-electromagnetic-lab/assets/41024075/d6e4286c-75ee-40f7-bd9a-00b0c45877d4

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.16/phet/faradays-electromagnetic-lab_all_phet.html
Version: 1.0.0-dev.16 2024-03-01 00:38:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment] 2024-03-01 19:25
Thanks for reporting @KatieWoe. Normally, this sort of thing would absolutely be a bug, but in this case, it's the intended behavior.

Faraday's Law and the Java version of FEL impose collision detection on the magnet/coil. We decided against using collision detection in this sim for the reasons outlined in https://github.com/phetsims/faradays-electromagnetic-lab/issues/10#issuecomment-1901277267. 

> We also discussed collision detection, and we recommend NOT implementing collision detection for the HTML5 version. We'll run this decision past the team. But the reasons are:
>
>(1) The only place we planned to have collision detection was between bar magnet and pickup coil in the _Pickup Coil_ screen.
>(2) The collision detection code in the Java version was complicated, and caused continuous problems and bug reports. It would likely be the same in the HTML5 version.
>(3) In other screens, things magically move through the pickup coil, so why not the bar magnet too?
>(4) Collision detection create a usability hurdle for accessibility (probably the most compelling argument for leaving it out).

Closing as wont-fix.

**Closed as not planned by arouinfar** 2024-03-01 19:25 UTC
Labels: type:bug, type:wontfix
