### ISSUE TITLE
Horizontal barrier prevents magnet from moving up on screen

### ISSUE THREAD

**Issue by Luisav1** [phetsims/faradays-electromagnetic-lab#199] opened 2024-07-24 15:36 UTC
### Test Device

iPhone

### Operating System

iOS 17.5.1

### Browser

Safari

### Problem Description

For https://github.com/phetsims/qa/issues/1116.
There is sometimes a horizontal barrier on the Bar Magnet screen where the earth or magnet can't move past and upwards from.

### Steps to Reproduce

1. Load the sim on Safari on an iPhone.
2. Rotate the phone vertically and horizontally a few times while moving around the magnet / earth.
3. The magnet / earth can sometimes get stuck.
The lower you move the magnet / earth, a new lower horizontal barrier is set where you let it go.

### Visuals

https://github.com/user-attachments/assets/b27dbca5-b467-4389-845d-9f91fa40664c

<details>
<summary><b>Troubleshooting Information</b></summary>

!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-rc.1/phet/faradays-electromagnetic-lab_all_phet.html
Version: 1.0.0-rc.1 2024-07-18 17:36:37 UTC
Features missing: applicationcache, applicationcache, fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1
Language: en-CA
Window: 980x1557
Pixel Ratio: 3/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}******

</details>

**Comment by pixelzoom** [comment] 2024-07-24 17:04
Unless I'm misunderstanding something, this is the expected behavior.  By design, magnets and pickup coil have dragBounds described as follows (where rightPanels are the panels at the right side of the screen):

* left: layoutBounds.left
* right: rightPanels.left
* top: layoutBounds.top
* bottom: layoutBounds.bottom

The position of bar magnet (center), electromagnet (center of the coil), and pickup coil (center of the coil) is constrained to stay within these dragBounds.

Running with `?dev` shows layoutBounds as a red rectangle.  Here are examples from desktop.

In landscape mode, this bar magnet is dragged as far left as possible:

<img width="1019" alt="screenshot_3423" src="https://github.com/user-attachments/assets/7af308ab-1e50-41f8-aff9-517d33660a19">

In landscape mode, this bar magnet is dragged as far left as possible, and the pickup coil is dragged as far right as possible:

<img width="1016" alt="screenshot_3424" src="https://github.com/user-attachments/assets/55ba9060-9915-432c-9de9-4148ad9ce5ca">

In portrait mode, this bar magnet is dragged as far down as possible:

<img width="604" alt="screenshot_3421" src="https://github.com/user-attachments/assets/72bec904-d67a-415d-b934-b9fec6560d78">

In portrait mode, this bar magnet is dragged as far down as possible, and the pickup coil is dragged as far up as possible:

<img width="616" alt="screenshot_3425" src="https://github.com/user-attachments/assets/109dd025-238b-4b76-bdd5-e6319d460760">

The compass and field meter have different dragBounds constraints. Their positions must be inside the visibleBounds of the screen. If the screen is resized such that the compass (or field meter) would be outside the visibleBounds, then it is a automatically moved so that it is inside the dragBounds.

@Luisav1 does that explain what you've reported? If not, let's discuss on Zoom.

**Comment by pixelzoom** [comment] 2024-07-24 17:11
I should also note the reason why the magnets and pickup coils have these dragBounds constraints.  Unlike the compass and field meter, moving the magnet or pickup coil automatically (when the browser window is resized) introduces all kinds of problems for the model and PhET-iO.   And there's no pedagogical advantage to supporting something other than layoutBounds, and wndow sizes other than layoutBounds are considered unusual.  So we limit to layoutBounds to avoid these problems.

**Comment by pixelzoom** [comment] 2024-07-25 15:51
Watching the video again that @Luisav1 posted in https://github.com/phetsims/faradays-electromagnetic-lab/issues/199#issue-2427899666, I suspect that I don't understand what she has reported.  It looks like the magnet is stuck at one horizontal position (can only be moved left/right) and I can't reproduce it.  I don't understand why the entire browser window appears to be moving up and down in the video.  And I don't see the phone being rotated in the video. 

@arouinfar Thoughts on what might be going on here?

**Comment by pixelzoom** [comment] 2024-07-25 15:52
@arouinfar Thoughts on what might be going on here?

**Comment by arouinfar** [comment] 2024-07-25 17:22
According to the steps to reproduce, it looks like @Luisav1 is moving the magnet while rotating the phone. I can't reproduce on my phone (unsupported platform) or iPad. 

@pixelzoom I'm inclined to do nothing here. It's definitely an edge case, and not something either of us are able to reproduce.

**Comment by pixelzoom** [comment] 2024-07-25 19:25
Thanks @arouinfar.  Closing as "won't fix".

**Closed as completed by pixelzoom** 2024-07-25 19:25 UTC
Labels: type:bug, type:wontfix
