### ISSUE TITLE
Artifacts in PhET-iO wrappers on iPad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#197] opened 2024-07-17 17:38 UTC
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.5.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1110 I see some artifacts as I test the different PhET-iO wrappers--state, active, multi, screenshot and data: textarea. I don't see an issue with the standalone. I also don't see an issue with the PhET brand (I even tested the iframe) or on mac+safari. 
The artifacts are minor compared to https://github.com/phetsims/faradays-electromagnetic-lab/issues/172 and most obvious when moving the Field Meter but do happen when moving the Coil as well.

**Steps to reproduce**
1. Open the Data Stream wrapper 
2. Turn on Projector Mode in preferences (optional)
3. Go to any screen and check the Field Meter
4. Move the Field Meter around the screen. 

**Visuals**

![file](https://github.com/user-attachments/assets/86fa8477-7227-4d9b-9533-efef62f23578)

**Comment by pixelzoom** [comment] 2024-07-17 17:53
I could NOT reproduce on my iPad6 with iPadOS 17.5.1.  I tested [1.0.0-dev.39](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.39/phet-io/) with the State, Active, and Data:textarea wrappers.  And as @Nancy-Salpepi confirmed, it does not occur in Standalone.

I also do NOT see this problem on macOS (Safari, Chrome, Firefox).  @Nancy-Salpepi could you confirm whether you see this problem on any desktop platform?  I see that you ruled out "on mac+safari", but how about Windows?

If this problem does NOT occur on desktop platforms, I recommend that we close this issue at "won't fix", since PhET-iO wrappers (other than Standalone) are not intended to be used by clients on an iPad.  @arouinfar @zepumph do you agree?

**Comment by Nancy-Salpepi** [comment] 2024-07-17 18:03
It doesn't occur on my mac with chrome/safari/FF or with Win 10 + chrome/FF.

**Comment by arouinfar** [comment] 2024-07-17 19:57
I couldn't reproduce on macOS/Safari.

> If this problem does NOT occur on desktop platforms, I recommend that we close this issue at "won't fix", since PhET-iO wrappers (other than Standalone) are not intended to be used by clients on an iPad. @arouinfar @zepumph do you agree?

Sounds good to me @pixelzoom.

**Comment by pixelzoom** [comment] 2024-07-17 21:52
@zepumph does it seem reasonable to close this as "won't fix" ?

**Closed as completed** 2024-07-18 16:21 UTC
Labels: type:bug, type:wontfix, dev:phet-io
